---
- name: Deploy Application
  hosts: local

  vars:
    exec: bin/server-dist

  tasks:
    - name: Compile Application
      make:
        chdir: .
        target: "{{ exec }}"
      register: compiler

    - name: Execute Application
      ansible.builtin.shell: "./{{ exec }} &"
      when: not compiler.failed
...
