- name: Deploy Application
  hosts: localhost

  vars:
    workdir: ../application
    executable: bin/app

  pre_tasks:
    - ansible.builtin.shell:
        cmd: ps cx | grep app | awk '{print $1}'
      register: proc

    - ansible.builtin.shell: 
        cmd: "kill -9 {{ proc.stdout }}"
      when: proc.rc

  tasks:
    - name: Compile
      make:
        target: "{{ executable }}"
        chdir: "{{ workdir }}"
      register: compiler

    - name: Execute
      ansible.builtin.shell:
        cmd: "{{ executable }} &"
        chdir: "{{ workdir }}"
      when: not compiler.failed
